package com.sbnz;

import com.sbnz.studycalendarapp.model.Obligation;
import com.sbnz.studycalendarapp.model.Subject;
import com.sbnz.studycalendarapp.model.Student;
import com.sbnz.studycalendarapp.enums.StudentActivity;
import java.util.List;

global List<Obligation> $finishedObligations;

rule "Finished obligations and earned points"
    when
    	$s: Subject($obligations: obligations)
        accumulate(
       		Obligation($o: this, finished, $earnedPoints: earnedPoints) from $obligations,
       		$finished: collectList($o),
       		$points: sum($earnedPoints)
    	)
    then
    	$finishedObligations.addAll($finished);
    	modify($s) {setEarnedPoints($points)};
end

rule "All subject's obligations are finished"
    when
    	$s: Subject($id: id, $obligationsNum: obligations.size())
    	accumulate(
       		Obligation($o: this, subject.id == $id) from $finishedObligations,
       		$finishedForSubject: count($o)
    	)
    	eval($finishedForSubject == $obligationsNum)
    then
    	modify($s) {setFinished(true)};
end

rule "Student's points for finished and passed obligations"
	no-loop
    when
    	$s: Student($activityPoints: activityPoints)
    	$o: Obligation(finished, passed, $earnedPoints: earnedPoints, $priority: priority)
    then
    	modify($s) {setActivityPoints($activityPoints + 10 * (5 - $priority) + $earnedPoints)};
end

rule "Student's points for skipped obligations"
	no-loop
    when
    	$s: Student($activityPoints: activityPoints)
    	$o: Obligation(skipped, $priority: priority)
    then
    	modify($s) {setActivityPoints($activityPoints - 10 * (5 - $priority))};
end
